let products = [
    {
        "images": "images/file.jpg",
        "subject": "Physics",
        "price": 50,
        "location": "Geneva",
        "availableInventory": 5,
    },
    {
        "images": "images/che.png",
        "subject": "Chemistry",
        "price": 35,
        "location": "Lagos",
        "availableInventory": 5,
    },
    {
        "images": "images/bio.jpg",
        "subject": "Biology",
        "price": 38,
        "location": "Abuja",
        "availableInventory": 5,
    },
    {
        "images": "images/psy.jpg",
        "subject": "Psychology",
        "price": 39,
        "location": "Ontario",
        "availableInventory": 5,
    },
    {
        "images": "images/geo.png",
        "subject": "Geography",
        "price": 42,
        "location": "Granada",
        "availableInventory": 5,
    },
    {
        "images": "images/zoo.jpg",
        "subject": "Zoology",
        "price": 49,
        "location": "Conackry",
        "availableInventory": 5,
    },
    {
        "images": "images/eng.jpg",
        "subject": "Engineering",
        "price": 38,
        "location": "Munich",
        "availableInventory": 5,
    },
    {
        "images": "images/com.jpg",
        "subject": "Computer",
        "price": 41,
        "location": "Timbuktu",
        "availableInventory": 5,
    },
    {
        "images": "images/mat.jpg",
        "subject": "Mathematics",
        "price": 47,
        "location": "Abuja",
        "availableInventory": 5,
    },
    {
        "images": "images/soc.png",
        "subject": "Sociology",
        "price": 26,
        "location": "Toronto",
        "availableInventory": 5,
    },
]
