let products = [
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/file.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/che.png",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/bio.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
       "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/psy.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/geo.png",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/zoo.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/eng.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/com.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/mat.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/product-math.png",
        "availableInventory": 5, 
        "rating": 5,
    },
]

